include Makefile.defaults

# link statically with musl-libc
CC = /home/manuel/Work/musl/bin/musl-gcc
CFLAGS := -fPIC -Wall -Werror

lib: lib$(NAME).$(VERSION).so

lib$(NAME).$(VERSION).so: $(NAME).o
	$(CC) -shared -static -o lib$(NAME)-linux64.so $^

$(NAME)_test: lib$(NAME).$(VERSION).so
	$(CC) lsd_call_example.c -o $@ -L. -l$(NAME)

test: $(NAME)_test
	LD_LIBRARY_PATH=. ./$(NAME)_test
