# to compile a x86_64 lib in an ubuntu i386 box
include Makefile.defaults

# link statically with musl-libc
CC = /home/manuel/tabula-build/musl-64/bin/musl-gcc
CFLAGS := -fPIC -Wall -Werror -m64

lib: lib$(NAME).$(VERSION).so

lib$(NAME).$(VERSION).so: $(NAME).o
	@LDEMULATION=elf_x86_64 $(CC) -m64 -shared -static -o lib$(NAME)-linux64.so $^

