include Makefile.defaults

lib: lib$(NAME).$(VERSION).so

lib$(NAME).$(VERSION).so: $(NAME).o
	$(CC) -shared -lm -o lib$(NAME).so $^

$(NAME)_test: lib$(NAME).$(VERSION).so
	$(CC) lsd_call_example.c -o $@ -L. -l$(NAME)

test: $(NAME)_test
	LD_LIBRARY_PATH=. ./$(NAME)_test
